[package]
name = "hit-detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = "0.5.0"
clap = { version = "4.1.6", features = ["unicode"] }
image = "0.24.5"
rayon = "1.6.1"
